return {
 ["author"]="Tomáš Kruliš",
 ["htmlfiles"]={ "orgModeAndPandocForTechnicalWriting_ConTeXt-div.html" },
 ["htmlroot"]="orgModeAndPandocForTechnicalWriting_ConTeXt-div.html",
 ["identifier"]="833b32eb-45af-b080-1fbc-e81140f9285f",
 ["imagefile"]="styles/orgModeAndPandocForTechnicalWriting_ConTeXt-images.css",
 ["imagepath"]="images",
 ["images"]={
  ["image>1"]={
   ["element"]="image",
   ["height"]="2.800cm",
   ["id"]="image-1",
   ["name"]="../pictures/git-basics_snapshots.png",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/git-basics_snapshots.png",
   ["used"]="",
   ["width"]="3.733cm",
  },
  ["image>2"]={
   ["element"]="image",
   ["height"]="2.800cm",
   ["id"]="image-2",
   ["name"]="../pictures/git-basics_areas.png",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/git-basics_areas.png",
   ["used"]="",
   ["width"]="3.733cm",
  },
  ["image>3"]={
   ["element"]="image",
   ["height"]="2.800cm",
   ["id"]="image-3",
   ["name"]="../pictures/git-basics_lifecycle.png",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/git-basics_lifecycle.png",
   ["used"]="",
   ["width"]="3.733cm",
  },
 },
 ["language"]="en",
 ["metadata"]={},
 ["name"]="orgModeAndPandocForTechnicalWriting_ConTeXt",
 ["stylepath"]="styles",
 ["styles"]={ "orgModeAndPandocForTechnicalWriting_ConTeXt-defaults.css", "orgModeAndPandocForTechnicalWriting_ConTeXt-images.css", "orgModeAndPandocForTechnicalWriting_ConTeXt-styles.css" },
 ["title"]="Org-mode and Pandoc for Technical Writing",
 ["xhtmlfiles"]={ "orgModeAndPandocForTechnicalWriting_ConTeXt-tag.xhtml" },
 ["xmlfiles"]={ "orgModeAndPandocForTechnicalWriting_ConTeXt-raw.xml" },
}